<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="fizzbuzz_tests.fizzBuzzTest-20181018144534" skipped="0" tests="9" time="0.002" timestamp="2018-10-18T14:45:34">
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_10_is_buzz" time="0.000" timestamp="2018-10-18T14:45:34"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_15_is_fizzbuzz" time="0.000" timestamp="2018-10-18T14:45:34"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_3_is_fizz" time="0.000" timestamp="2018-10-18T14:45:34"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_4_is_4" time="0.000" timestamp="2018-10-18T14:45:34"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_5_is_buzz" time="0.000" timestamp="2018-10-18T14:45:34"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_9_is_fizz" time="0.000" timestamp="2018-10-18T14:45:34"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizzbuzz_list_is_initialized" time="0.000" timestamp="2018-10-18T14:45:34"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizzbuzz_start_sets" time="0.000" timestamp="2018-10-18T14:45:34"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizzbuzz_throws_value_error_for_no_start_value" time="0.001" timestamp="2018-10-18T14:45:34">
		<error message="__init__() takes 1 positional argument but 2 were given" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/Users/mikebmc/Documents/job_hunting_2018/applications/Intersection/nr_real_fizzbuzz/src/unittest/python/fizzbuzz_tests.py", line 45, in test_if_fizzbuzz_throws_value_error_for_no_start_value
    fizzBuzz(20)
TypeError: __init__() takes 1 positional argument but 2 were given
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
